version: "3.2"

services:
  alice:
    build: .
    container_name: delta-chain-alice
    image: deltampc/delta-chain:dev
    command:
      - --validator
      - --unsafe-ws-external
      - --unsafe-rpc-external
      - --rpc-methods
      - Unsafe
      - --name
      - Alice
      - --node-key-file
      - /root/.local/node-key
    ports:
      - "9944:9944"
      - "9933:9933"
    volumes:
      - type: bind
        source: ./.local/alice
        target: /root/.local
  bob:
    container_name: delta-chain-bob
    image: deltampc/delta-chain:dev
    command:
      - --validator
      - --unsafe-ws-external
      - --unsafe-rpc-external
      - --rpc-methods
      - Unsafe
      - --name
      - Bob
      - --port
      - "30334"
      - --ws-port
      - "9945"
      - --rpc-port
      - "9934"
      - --node-key-file
      - /root/.local/node-key
      - --bootnodes
      - /dns/alice/tcp/30333/p2p/12D3KooWKpxeRfkRPmCQUb9PCBVPgdo139n3g8SNAKE3Ap4V6bWy
    ports:
      - "9945:9945"
      - "9934:9934"
    volumes:
      - type: bind
        source: ./.local/bob
        target: /root/.local
