version: "3.2"

services:
  alice:
    build: .
    container_name: delta-chain-alice
    image: registry.cn-shanghai.aliyuncs.com/yuanben/delta-chain:0.0.1
    command:
      - --validator
      - --unsafe-ws-external
      - --unsafe-rpc-external
      - --rpc-methods
      - Unsafe
      - --name
      - Alice
      - --node-key
      - 2d2c7a1c5b92fc77aef5524851fc301d91a0a958bb68a9a5fe617e5a8e9f66d6
    ports:
      - "9944:9944"
      - "9933:9933"
    volumes:
      - type: bind
        source: ./.local/alice
        target: /root/.local
  bob:
    container_name: delta-chain-bob
    image: registry.cn-shanghai.aliyuncs.com/yuanben/delta-chain:0.0.1
    command:
      - --validator
      - --unsafe-ws-external
      - --unsafe-rpc-external
      - --rpc-methods
      - Unsafe
      - --name
      - Bob
      - --port
      - "30334"
      - --ws-port
      - "9945"
      - --rpc-port
      - "9934"
      - --node-key
      - 41a86336376cde451ae861f4d89e42b8e9fec9d2174a1860451f7300d02b284d
      - --bootnodes
      - /dns/alice/tcp/30333/p2p/12D3KooWKpxeRfkRPmCQUb9PCBVPgdo139n3g8SNAKE3Ap4V6bWy
    ports:
      - "9945:9945"
      - "9934:9934"
    volumes:
      - type: bind
        source: ./.local/bob
        target: /root/.local
