name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: 'Run Rust tests'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Submodules
      run: git submodule update --init --recursive
    - name: Init
      run: |
        scripts/init.sh
        cargo --version
        rustc --version
        cargo +$WASM_BUILD_TOOLCHAIN --version
        rustc +$WASM_BUILD_TOOLCHAIN --version
      env:
        WASM_BUILD_TOOLCHAIN: nightly-2021-07-06
    - name: Run tests
      run: cargo test --locked --verbose --all
  integration:
    name: 'Run integration tests'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Submodules
      run: git submodule update --init --recursive
    - name: Init
      run: |
        scripts/init.sh
        cargo --version
        rustc --version
        cargo +$WASM_BUILD_TOOLCHAIN --version
        rustc +$WASM_BUILD_TOOLCHAIN --version
      env:
        WASM_BUILD_TOOLCHAIN: nightly-2021-07-06
    - name: Build manual seal client
      run: cd template/node && cargo build --release --locked --verbose --no-default-features --features manual-seal
    - name: Use Node.js 10
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: Install functional tests typescript
      run: cd ts-tests && npm install
    - name: Run functional tests
      run: cd ts-tests && npm run build && npm run test
  lint:
    name: 'Run lints'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Submodules
      run: git submodule update --init --recursive
    - name: Init
      run: |
        scripts/init.sh
        cargo --version
        rustc --version
        cargo +$WASM_BUILD_TOOLCHAIN --version
        rustc +$WASM_BUILD_TOOLCHAIN --version
      env:
        WASM_BUILD_TOOLCHAIN: nightly-2021-07-06
    - name: Rustfmt
      run: cargo fmt --all -- --check
